### ISSUE TITLE
Route not exposed

### ISSUE THREAD

**Issue by Sebsii** [elements-at/AlternateObjectTrees#20]
# Description
AdminController extends from DataObjectHelperController, which causes the routes to be overwritten. This leads to problems when trying to open an Object, because the route can not be resolved anymore.

# Solution
```yaml
_elements_alternate_object_trees:
    resource: "@ElementsAlternateObjectTreesBundle/Controller/"
    type:     annotation
    options:
        expose: true
```
